---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

filters:
  # filter instance that is dev, not prod
  tag:Name: dev*
  instance-state-name: running

# group instance by tags OR instance_type as example
# then use this group insteas of pointing to all instances
keyed_groups:
  - key: tags # 
    prefix: tag
  - key: instance_type
    prefix: instance_type 


